<div class="title-admin">Gestion d'ajout Arcs</div>

<a title="Modifier les arcs" href="index.php?page=admin_list_arc" class="lien-modif">Modifier les Arcs</a>

<form class="formulaire" method="POST" enctype="multipart/form-data">
    <label>Nom</label>
    <input type="text" name="name" required/>
    
    <label>Description</label>
    <textarea name="description" required></textarea>
    
    <label>Image</label>
    <input type="file" name="picture"/>
    
    <button type="submit">Valider</button>
    
</form>