<div class="title-admin">Modifiez votre personnage selectionné</div>

<form class="formulaire" method="POST" enctype="multipart/form-data">
    <label>Nom</label>
    <input type="text" name="name" required/>
    
    <label>Description</label>
    <textarea name="description" required></textarea>
    
    <label>Image</label>
    <input type="file" name="picture"/>
    
    <button type="submit">Valider</button>
    <a title="retour" class="annuler-modifier" href="index.php?page=admin_list_character">annuler</a>
    
</form>