
    <div class="reseaux-enfant">
        <a title="facebook" href="https://www.facebook.com/DemonSlayer.anime/" target="_blank">
            <i class="fab fa-facebook-f"></i>
        </a>
        <a title="instagram" href="https://instagram.com/demonslayer_hc?igshid=YmMyMTA2M2Y=" target="_blank">
            <i class="fab fa-instagram"></i>
        </a>
        <a title="page d'accueil" href="index.php">
            <i class="fas fa-home"></i>
        </a>
        <a title="youtube" href="https://www.youtube.com/watch?v=Ogr9pOY8Wew" target="_blank">
            <i class="fab fa-youtube"></i>
        </a>
        <a title="linkedin" href="https://www.linkedin.com/in/julien-ledoux-9a35b7235/" target="_blank">
            <i class="fab fa-linkedin"></i>
        </a>
    </div>

<script src="./js/contact.js"></script>